---
- name: Ensure Package-Manager is up to date
  package:
    update_cache: yes
    cache_valid_time: 3600

- name: Install exim packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ exim_packages }}"
  notify: restart exim
