---
- name: Install sendmail packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ sendmail_packages }}"
  notify: restart sendmail
  when: install_sendmail_default_packages

- name: Install sendmail additional packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ sendmail_additional_packages }}"
  notify: restart sendmail

