---
- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
      - "{{ ansible_distribution }}.yml"
      skip: true
  tags: vars

- name: check sendmail and exim variables
  assert:
    that: install_sendmail != install_exim
    msg: "Either install sendmail or install exim. Both is not possible!"
  when: install_sendmail == true or install_exim == true
