---
- name: start sendmail
  service:
    name: sendmail
    state: started
    enabled: yes

- name: restart sendmail
  service:
    name: sendmail
    state: restarted
    enabled: yes

- name: restart exim
  service:
    name: exim4
    state: restarted
    enabled: yes
